#!/usr/bin/env node
// build-tokens.mjs — Token pipeline (ADR-0001)
// primitives.json + semantic.json -> src/styles/tokens.gen.css + src/ui/tokens/tokens.gen.ts
// Validate: tên token, contrast AA/AAA (WCAG 2.1) cho cặp chữ/nền semantic.
// --check: chỉ so output với file đã commit (dùng trong prebuild), không ghi.

import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const TOK = join(ROOT, "src", "ui", "tokens");
const OUT_CSS = join(ROOT, "src", "styles", "tokens.gen.css");
const OUT_TS = join(ROOT, "src", "ui", "tokens", "tokens.gen.ts");
const CHECK = process.argv.includes("--check");

const primitives = JSON.parse(readFileSync(join(TOK, "primitives.json"), "utf8"));
const semantic = JSON.parse(readFileSync(join(TOK, "semantic.json"), "utf8"));

// ── helpers ──
const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

function hexToRgb(hex) {
  let h = hex.replace("#", "");
  if (h.length === 3) h = h.split("").map((c) => c + c).join("");
  if (h.length !== 6) return null; // 8-digit/other: bỏ qua contrast check
  return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16));
}
function relLuminance([r, g, b]) {
  const f = (c) => {
    c /= 255;
    return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
  };
  return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b);
}
function contrast(a, b) {
  const l1 = relLuminance(a), l2 = relLuminance(b);
  return (Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05);
}

// ── validate primitives ──
const errors = [];
const colorValues = {};
for (const [group, entries] of Object.entries(primitives)) {
  if (group.startsWith("_")) continue;
  for (const [name, def] of Object.entries(entries)) {
    if (!def || typeof def.value !== "string") errors.push(group + "." + name + ": thiếu .value");
    if (group === "color") colorValues[name] = def.value;
  }
}

// ── validate semantic: mọi mode phải có đủ role ──
const modes = semantic.modes || [];
for (const [role, perMode] of Object.entries(semantic.roles)) {
  if (role.startsWith("_")) continue;
  for (const mode of modes) {
    if (!(mode in perMode)) errors.push("semantic." + role + ": thiếu mode '" + mode + "'");
  }
}
// Contrast pairs bắt buộc: (chữ, nền, min ratio)
const CONTRAST_PAIRS = [
  ["content-primary", "surface-page", 4.5],
  ["content-secondary", "surface-panel", 4.5],
  ["content-on-win", "surface-win", 7.0],
  ["chrome-titletext", "chrome-titlebar", 4.5],
];
const contrastReport = [];
for (const [fgRole, bgRole, min] of CONTRAST_PAIRS) {
  for (const mode of modes) {
    const fg = semantic.roles[fgRole] && semantic.roles[fgRole][mode];
    const bg = semantic.roles[bgRole] && semantic.roles[bgRole][mode];
    if (!fg || !bg) continue;
    const fgHex = colorValues[fg], bgHex = colorValues[bg];
    if (!fgHex || !bgHex) { errors.push("contrast: token màu '" + fg + "/" + bg + "' không tồn tại"); continue; }
    const rgbF = hexToRgb(fgHex), rgbB = hexToRgb(bgHex);
    if (!rgbF || !rgbB) continue;
    const ratio = contrast(rgbF, rgbB);
    contrastReport.push({ pair: fgRole + "/" + bgRole, mode, ratio: +ratio.toFixed(2), required: min });
    if (ratio < min) errors.push("contrast FAIL: " + fgRole + "/" + bgRole + " mode=" + mode + " ratio=" + ratio.toFixed(2) + " < " + min);
  }
}

// ── generate CSS ──
const css = [];
css.push("/* ═══════════════════════════════════════════════════════════");
css.push(" * tokens.gen.css — DO NOT EDIT (generated by scripts/build-tokens.mjs)");
css.push(" * Source: src/ui/tokens/{primitives,semantic}.json · ADR-0001");
css.push(" * Fingerprint: " + createHash("sha256").update(JSON.stringify({ primitives, semantic })).digest("hex").slice(0, 16));
css.push(" * ═══════════════════════════════════════════════════════════ */");
css.push("");
css.push(":root {");
css.push("  /* ── primitives.color ── */");
for (const [name, def] of Object.entries(primitives.color)) {
  if (name.startsWith("_")) continue;
  css.push("  --color-" + kebab(name) + ": " + def.value + ";");
}
for (const group of ["space", "touchTarget", "radius", "zIndex", "duration", "easing", "shadowGlow"]) {
  css.push("  /* ── primitives." + group + " ── */");
  for (const [name, def] of Object.entries(primitives[group] || {})) {
    if (name.startsWith("_")) continue;
    // CSS custom property khong chap nhan "." — escape thanh "-half"
    const safe = kebab(name).replaceAll(".", "-half");
    css.push("  --" + kebab(group).replace("touch-target", "touch") + "-" + safe + ": " + def.value + ";");
  }
}
css.push("  /* ── primitives.font ── */");
for (const [name, def] of Object.entries(primitives.font)) {
  if (name.startsWith("_")) continue;
  css.push("  --font-" + kebab(name) + ": " + def.value + ";");
}
css.push("");
css.push("  /* ── semantic roles (mode mặc định: catalog) ── */");
for (const [role, perMode] of Object.entries(semantic.roles)) {
  if (role.startsWith("_")) continue;
  const v = perMode.catalog !== undefined ? perMode.catalog : Object.values(perMode)[0];
  if (role === "glow-level") css.push("  --role-glow: var(--shadow-glow-" + v + ");");
  else css.push("  --role-" + role + ": var(--color-" + kebab(v) + ");");
}
css.push("}");
css.push("");
css.push("/* Mode overrides — gắn data-ui-mode lên <html> (xem ADR-0003) */");
for (const mode of modes.slice(1)) {
  css.push('[data-ui-mode="' + mode + '"] {');
  for (const [role, perMode] of Object.entries(semantic.roles)) {
    if (role.startsWith("_")) continue;
    const v = perMode[mode];
    if (v && v !== perMode.catalog) {
      if (role === "glow-level") css.push("  --role-glow: var(--shadow-glow-" + v + ");");
      else css.push("  --role-" + role + ": var(--color-" + kebab(v) + ");");
    }
  }
  css.push("}");
  css.push("");
}
const cssText = css.join("\n") + "\n";

// ── generate TS ──
const ts = [];
ts.push("// tokens.gen.ts — DO NOT EDIT (generated by scripts/build-tokens.mjs) · ADR-0001");
ts.push("");
ts.push("export const COLOR_TOKENS = {");
for (const name of Object.keys(primitives.color)) {
  if (name.startsWith("_")) continue;
  ts.push("  " + name + ': "var(--color-' + kebab(name) + ')",');
}
ts.push("} as const;");
ts.push("");
ts.push("export const Z_INDEX = {");
for (const name of Object.keys(primitives.zIndex)) {
  ts.push("  " + name + ': "var(--z-index-' + kebab(name) + ')" as const,');
}
ts.push("};");
ts.push("");
ts.push("export const UI_MODES = [" + modes.map((m) => '"' + m + '"').join(", ") + "] as const;");
ts.push("export type UIMode = (typeof UI_MODES)[number];");
const tsText = ts.join("\n") + "\n";

// ── check mode ──
if (CHECK) {
  const drift = [];
  try {
    if (readFileSync(OUT_CSS, "utf8") !== cssText) drift.push(relative(ROOT, OUT_CSS));
  } catch { drift.push(relative(ROOT, OUT_CSS) + " (missing)"); }
  try {
    if (readFileSync(OUT_TS, "utf8") !== tsText) drift.push(relative(ROOT, OUT_TS));
  } catch { drift.push(relative(ROOT, OUT_TS) + " (missing)"); }
  if (errors.length) {
    console.error("build-tokens: VALIDATION FAIL");
    for (const e of errors) console.error("  x " + e);
    process.exit(1);
  }
  if (drift.length) {
    console.error("build-tokens: gen files lệch với token source: " + drift.join(", "));
    console.error('  -> chạy "npm run tokens" để regenerate, rồi commit.');
    process.exit(2);
  }
  console.log("build-tokens: OK (" + contrastReport.length + " contrast pairs pass)");
  process.exit(0);
}

// ── write mode ──
if (errors.length) {
  console.error("build-tokens: VALIDATION FAIL");
  for (const e of errors) console.error("  x " + e);
  process.exit(1);
}
writeFileSync(OUT_CSS, cssText, "utf8");
writeFileSync(OUT_TS, tsText, "utf8");
console.log("build-tokens: wrote " + relative(ROOT, OUT_CSS) + " + " + relative(ROOT, OUT_TS));
for (const c of contrastReport) console.log("  OK " + c.pair + " [" + c.mode + "] ratio=" + c.ratio + " (min " + c.required + ")");
